# Generated by Django 4.2 on 2023-04-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
