# Generated by Django 4.2 on 2023-04-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_pol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
    ]
